{{- if not .Values.config.createK8sSecretConfig }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "jds-common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
{{- if .Values.config.annotations }}
  annotations:
{{ toYaml .Values.config.annotations | indent 4 }}
{{- end }}
  labels: {{- include "jds-common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "jds-common.tplValues.render" ( dict "value" .Values.commonLabels "scope" $ ) | nindent 4 }}
    {{- end }}
{{- if .Values.config.labels }}
{{ toYaml .Values.config.labels | indent 4 }}
{{- end }}
data:
  sql_exporter.yml: |
{{- $root := . }}
    # Global settings and defaults.
    global:
    {{- with .Values.config }}
      scrape_timeout: {{ default "10s" .scrapeTimeout }}
      scrape_timeout_offset: {{ default "500ms" .scrapeTimeoutOffset }}
      scrape_error_drop_interval: {{ default "0s" .scrapeErrorDropInterval }}
      min_interval: {{ default "0ms" .minInterval }}
      max_connections: {{ default 3 .maxConnections }}
      max_idle_connections: {{ default 3 .maxIdleConnections }}
      max_connection_lifetime: {{ .maxConnectionLifetime }}

    {{ with .collectorFiles -}}
    collector_files:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    # The target to monitor and the list of collectors to execute on it.
    target:
      # ** If the SQLEXPORTER_TARGET_DSN environment variable is set, this data source will be ignored. **
      data_source_name: {{ default "sqlserver://user:pass@dbserver:1433" .dataSourceName | squote }}

    {{- if .awsSecretName }}
      {{ print "aws_secret_name: " (.awsSecretName | squote) | nindent 6 }}
    {{- end }}

      collectors:
      {{- if .collectorNames }}
        {{- range .collectorNames }}
          {{- print "- " . | nindent 8 }}
        {{- end }}
      {{- else }}
        {{ required "At least 1 (one) collector name must be defined in `collectorNames`" .collectorNames }}
      {{- end }}

    {{- end }}

    collectors:
    {{- if .Values.collectorDefs }}
      {{- tpl .Values.collectorDefs $root | nindent 6 }}
    {{ else }}
      {{ required "At least 1 (one) collector definition must be defined in `collectorDefs`" .Values.collectorDefs }}
    {{- end }}
{{- end }}

