kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ printf "%s-config" (include "jdscommon.names.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "jdscommon.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "jdscommon.tplValues.render" ( dict "value" .Values.commonLabels "scope" $ ) | nindent 4 }}
    {{- end }}
data:
  sql_exporter.yml: |
{{- $root := . }}
    # Global settings and defaults.
    global:
    {{- with .Values.config }}
      scrape_timeout: {{ default "10s" .scrapeTimeout }}
      scrape_timeout_offset: {{ default "500ms" .scrapeTimeoutOffset }}
      min_interval: {{ default "0ms" .minInterval }}
      max_connections: {{ default 3 .maxConnections }}
      max_idle_connections: {{ default 3 .maxIdleConnections }}
      max_connection_lifetime: {{ .maxConnectionLifetime }}
    {{- end }}

    # The target to monitor and the list of collectors to execute on it.
    target:
      data_source_name: {{ default "sqlserver://user:pass@dbserver:1433" .Values.config.dataSourceName | squote }}

      collectors:
      {{- if .Values.config.collectorNames }}
        {{- range .Values.config.collectorNames }}
          {{- print "- " . | nindent 8 }}
        {{- end }}
      {{- else }}
        {{ required "At least 1 (one) collector name must be defined in `collectorNames`" .Values.config.collectorNames }}
      {{- end }}

    collectors:
    {{- if .Values.collectorDefs }}
      {{- tpl .Values.collectorDefs $root | nindent 6 }}
    {{ else }}
      {{ required "At least 1 (one) collector definition must be defined in `collectorDefs`" .Values.collectorDefs }}
    {{- end }}
