kind: Deployment
apiVersion: {{ include "jds-common.capabilities.deployment.apiVersion" . }}
metadata:
  name: {{ include "jds-common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
{{- if .Values.annotations }}
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
  labels: {{- include "jds-common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "jds-common.tplValues.render" ( dict "value" .Values.commonLabels "scope" $ ) | nindent 4 }}
    {{- end }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      app: {{ include "jds-common.names.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  {{- if .Values.strategy }}
  strategy: {{- toYaml .Values.strategy | nindent 4 }}
  {{- if .Values.strategy.rollingUpdate }}
    {{- toYaml .Values.strategy.rollingUpdate | nindent 4 }}
  {{- end }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ include "jds-common.names.fullname" . }}
    spec:
      volumes:
        - name: sql-exporter-config
          configMap:
            name: {{ include "jds-common.names.fullname" . }}
          {{- if .Values.extraVolumes }}
            {{- toYaml .Values.extraVolumes | nindent 8 }}
          {{- end }}
      containers:
        - name: sql-exporter
          {{- with .Values.image }}
          image: "{{- if contains ":" .repository -}}{{ .repository }}{{- else -}}{{- if .registry -}}{{ .registry }}/{{- end -}}{{ .repository }}:{{ default $.Chart.AppVersion .tag }}{{- end -}}"
          imagePullPolicy: {{ .pullPolicy | quote }}
          {{- end }}
          env:
            - name: SQLEXPORTER_CONFIG
              value: "/sql-exporter/sql_exporter.yml"
            {{- if .Values.extraEnv }}
              {{- toYaml .Values.extraEnv | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: 9399
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            tcpSocket:
              port: 9399
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- else if .Values.customLivenessProbe }}
          livenessProbe: {{- toYaml .Values.customLivenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbeEnabled }}
          readinessProbe: {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: sql-exporter-config
              mountPath: /sql-exporter
            {{- if .Values.extraVolumeMounts }}
              {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
