kind: Service
apiVersion: v1
metadata:
  name: {{ include "jds-common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  labels: {{- include "jds-common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "jds-common.tplValues.render" ( dict "value" .Values.commonLabels "scope" $ ) | nindent 4 }}
    {{- end }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
spec:
  ports:
  - name: {{ include "jds-common.names.fullname" . }}
    port: 9399
    targetPort: {{ default 9399 .Values.service.targetPort }}
    {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}{{ print "nodePort: " .Values.service.nodePort | nindent 4 }}{{ end }}
    protocol: TCP
  selector:
    app: {{ include "jds-common.names.fullname" . }}
  type: {{ default "ClusterIP" .Values.service.type }}
