apiVersion: v2
name: sql-exporter
version: 0.0.7
description: A Helm chart for the Prometheus SQL Exporter
type: application
keywords:
  - sql_exporter
  - prometheus_exporter
  - prometheus_sql_exporter
  - jdstone
home: https://github.com/jdstone/helm-charts
sources:
  - https://github.com/burningalchemist/sql_exporter
dependencies:
  - name: jds-common
    version: "0.1.2"
    repository: https://charts.jdstone.dev
    tags:
      - common
      - helper
      - template
      - function
      - jdstone
maintainers:
  - name: jdstone
    email: jdstone1+helm@gmail.com
appVersion: "0.10.0"
